# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-02 22:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SelldataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('customer', models.CharField(max_length=50, verbose_name='客户名')),
                ('size', models.CharField(blank=True, max_length=10, null=True, verbose_name='规格')),
                ('kilo', models.IntegerField(default=0, verbose_name='斤数')),
                ('price', models.IntegerField(default=0, verbose_name='价格')),
                ('totalprice', models.IntegerField(default=0, verbose_name='金额')),
                ('score', models.IntegerField(default=0, verbose_name='评分')),
                ('debts', models.CharField(max_length=10, verbose_name='是否欠账')),
            ],
            options={
                'verbose_name': '售货单数据',
                'verbose_name_plural': '售货单数据',
            },
        ),
        migrations.CreateModel(
            name='SellTableModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_kilos', models.IntegerField(default=0, verbose_name='总斤数')),
                ('total_price', models.IntegerField(default=0, verbose_name='总金额')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('selldata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datatables.SelldataModel', verbose_name='售货数据')),
            ],
            options={
                'verbose_name': '售货单',
                'verbose_name_plural': '售货单',
            },
        ),
    ]
